# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0736eb0cb313cd7e951f7acb36992b19b3573e5671eab3f18a585360013b118037073514c347f3a07aacc2dbc29afd1e1fddd7ad468c5a060dcd60ca503eaa21

test:
  secret_key_base: 37f0b50b390a4c93d8dea99bf2d0793c07ef15896a996b14de24e9a69cc08075834c8a11faa98e0a6834614b83e5a85a177f46c39ee609d0bd462269189f20f9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
